version: '3.8'

services:
  openhands:
    image: docker.all-hands.dev/all-hands-ai/openhands:0.13
    container_name: openhands-app
    platform: linux/amd64
    ports:
      - "3010:3000"
      - "32728:32728"
      - "5000:5000"
      - "35514:35514" 
      - "5001-5011:5001-5011"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/app/data
    environment:
      - SANDBOX_RUNTIME_CONTAINER_IMAGE=docker.all-hands.dev/all-hands-ai/runtime:0.13-nikolaik
      - LOG_ALL_EVENTS=true
      - HOST_DOCKER_INTERNAL=host.docker.internal
      - DOCKER_HOST=unix:///var/run/docker.sock
      - RUNTIME_HOST=http://host.docker.internal:35514
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      default:
        aliases:
          - openhands.local

networks:
  default:
    name: openhands_network
    driver: bridge